// <auto-generated />
using System;
using Bookish.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bookish.Migrations
{
    [DbContext(typeof(BookishContext))]
    [Migration("20210304122921_CreateForeignKeys")]
    partial class CreateForeignKeys
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bookish.Models.BookCheckedOutModel", b =>
                {
                    b.Property<int>("CopyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int?>("BookModelBookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LibrarianId")
                        .HasColumnType("int");

                    b.Property<int?>("LibrarianModelLibrarianId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserModelUserId")
                        .HasColumnType("int");

                    b.HasKey("CopyId");

                    b.HasIndex("BookModelBookId");

                    b.HasIndex("LibrarianModelLibrarianId");

                    b.HasIndex("UserModelUserId");

                    b.ToTable("BookCheckedOutModel");
                });

            modelBuilder.Entity("Bookish.Models.BookModel", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BookAuthor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookAvailableCopies")
                        .HasColumnType("int");

                    b.Property<int>("BookBorrowedCopies")
                        .HasColumnType("int");

                    b.Property<string>("BookTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BookTotalCopies")
                        .HasColumnType("int");

                    b.Property<int>("BookYear")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.ToTable("BookModel");
                });

            modelBuilder.Entity("Bookish.Models.LibrarianModel", b =>
                {
                    b.Property<int>("LibrarianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("LibrarianIsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LibrarianName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LibrarianId");

                    b.ToTable("LibrarianModel");
                });

            modelBuilder.Entity("Bookish.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountBorrowedByUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("UserDOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserModel");
                });

            modelBuilder.Entity("Bookish.Models.BookCheckedOutModel", b =>
                {
                    b.HasOne("Bookish.Models.BookModel", "BookModel")
                        .WithMany("BookCheckedOutModels")
                        .HasForeignKey("BookModelBookId");

                    b.HasOne("Bookish.Models.LibrarianModel", "LibrarianModel")
                        .WithMany("BookCheckedOutModels")
                        .HasForeignKey("LibrarianModelLibrarianId");

                    b.HasOne("Bookish.Models.UserModel", "UserModel")
                        .WithMany("BookCheckedOutModels")
                        .HasForeignKey("UserModelUserId");

                    b.Navigation("BookModel");

                    b.Navigation("LibrarianModel");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("Bookish.Models.BookModel", b =>
                {
                    b.Navigation("BookCheckedOutModels");
                });

            modelBuilder.Entity("Bookish.Models.LibrarianModel", b =>
                {
                    b.Navigation("BookCheckedOutModels");
                });

            modelBuilder.Entity("Bookish.Models.UserModel", b =>
                {
                    b.Navigation("BookCheckedOutModels");
                });
#pragma warning restore 612, 618
        }
    }
}
